export const site = {
  title: "幻想鄉立東方大學｜Touhou University",
  portraitSet: "set-a",
  pages: [
    {
      id: "home",
      output: "index.html",
      title: "幻想鄉立東方大學｜Touhou University",
      description: "幻想鄉立東方大學：一所把異變變成問題、讓人類與妖怪共同求知的幻想大學。",
      preload: {
        href: "assets/images/campus-hero-mobile.webp",
        srcset: "assets/images/campus-hero-mobile.webp 960w, assets/images/campus-hero.webp 1672w",
        sizes: "100vw",
      },
      sections: ["hero", "ticker", "audiences", "services", "about", "traditions", "faq", "closing"],
    },
    {
      id: "academics",
      output: "academics.html",
      title: "學術與教學｜幻想鄉立東方大學",
      description: "七所學院、完整課程目錄、學分、學費、師資與本學期尚未解決的學術問題。",
      eyebrow: "ACADEMIC AFFAIRS",
      heading: "學術與教學",
      lead: "七所學院不只共用校名，也共用一批不肯安分待在系所邊界內的問題。",
      links: [["academics", "七所學院"], ["faculty", "師資陣容"]],
      sections: ["academics", "faculty"],
    },
    {
      id: "admissions",
      output: "admissions.html",
      title: "招生與試驗｜幻想鄉立東方大學",
      description: "招生日期、線上填報、入學試驗與幻想鄉統一學力試驗。",
      eyebrow: "ADMISSIONS 2026",
      heading: "招生、申請與試驗",
      lead: "把問題帶來，選一條入學路線；試卷會計時，申請草稿則會在這台裝置上等你回來。",
      links: [["admissions", "招生案內"], ["entrance-exam", "入學試驗"], ["gaokao", "統一試驗"]],
      sections: ["admissions", "exam", "gaokao"],
    },
    {
      id: "research",
      output: "research.html",
      title: "研究成果｜幻想鄉立東方大學",
      description: "幻想鄉的結界、歷史、魔法、工程與符卡研究完整檔案。",
      eyebrow: "RESEARCH ARCHIVE",
      heading: "研究成果與公開檔案",
      lead: "成果不只列題目：方法、失敗、限制、訂正與仍然吵不完的結論都留在檔案裡。",
      links: [["research", "研究成果"]],
      sections: ["research"],
    },
    {
      id: "incidents",
      output: "incidents.html",
      title: "校園事件中心｜幻想鄉立東方大學",
      description: "審閱校園事件的證物與證詞，以可控研究模擬驗證假說，結案後連動校務快訊與校園 BBS。",
      eyebrow: "INCIDENT RESPONSE + METHODS LAB",
      heading: "校園事件中心與研究模擬",
      lead: "事件可以先被控制，結論必須能被推翻；至於結案後的爭論，校園 BBS 自有它的生命。",
      links: [["incident-center", "事件案卷"], ["incident-simulator", "研究模擬器"], ["incident-records", "結案與連動"]],
      sections: ["incidents"],
    },
    {
      id: "campus",
      output: "campus.html",
      title: "校園生活｜幻想鄉立東方大學",
      description: "互動校園地圖、永遠亭詳圖、校園風采、社團與 BBS。",
      eyebrow: "CAMPUS LIFE",
      heading: "校園、路線與共同生活",
      lead: "從博麗門到永遠亭，路線會隨交通方式與月相改變；校園裡的傳聞通常更快。",
      links: [["map", "校園地圖"], ["campus", "校園風采"], ["bbs", "校園 BBS"]],
      sections: ["map", "campus", "bbs"],
    },
    {
      id: "mytu",
      output: "mytu.html",
      title: "My TU 學籍中心｜幻想鄉立東方大學",
      description: "本機學籍、申請審查、校園履歷、選課、課表與學業成績紀錄。",
      eyebrow: "MY TU",
      heading: "學籍、選課與校園履歷",
      lead: "這台裝置記得你的申請、試驗、課程與校園事件；資料不必離開瀏覽器。",
      links: [["my-tu", "學籍中心"], ["course-registration", "選課與成績"]],
      sections: ["mytu"],
    },
    {
      id: "library",
      output: "library.html",
      title: "霧湖圖書館｜幻想鄉立東方大學",
      description: "搜尋霧湖圖書館館藏，借閱、預約、續借、歸還並查看本機借閱紀錄。",
      preload: { href: "assets/images/library.webp" },
      eyebrow: "MISTY LAKE LIBRARY",
      heading: "霧湖圖書館",
      lead: "館藏可能飛離書架、拒絕原位置或只在滿月可見；索書號與你的借閱紀錄仍會留下。",
      links: [["library", "館藏與借閱"]],
      sections: ["library"],
    },
    {
      id: "housing",
      output: "housing.html",
      title: "宿舍與室友｜幻想鄉立東方大學",
      description: "比較五座學生宿舍，提交住宿需求，查看房間與室友配對，接受分房並申請換房。",
      eyebrow: "RESIDENTIAL LIFE",
      heading: "宿舍、房間與室友",
      lead: "月相、翼展、水域、牆面與作息都會影響分房；適合的室友不是沒有麻煩，而是麻煩能先談清楚。",
      links: [["housing", "宿舍總覽"], ["housing-application", "申請與配對"], ["housing-account", "我的宿舍"]],
      sections: ["housing"],
    },
  ],
  styles: [
    "core",
    "faculty-friction",
    "schools",
    "services",
    "traditions",
    "chronicle",
    "exam",
    "map",
    "forms",
    "bbs",
    "responsive-extras",
    "search",
    "audiences",
    "mytu",
    "courses",
    "pages",
    "library",
    "housing",
    "incidents",
    "eientei",
    "gaokao",
  ],
  locales: ["zh-Hant", "ja", "en"],
};
