export const site = {
  title: "幻想鄉立東方大學｜Touhou University",
  portraitSet: "set-a",
  sections: [
    "chrome",
    "hero",
    "ticker",
    "audiences",
    "services",
    "mytu",
    "about",
    "traditions",
    "academics",
    "faculty",
    "admissions",
    "exam",
    "gaokao",
    "map",
    "research",
    "campus",
    "bbs",
    "faq",
    "closing",
    "footer",
    "dialogs",
  ],
  styles: [
    "core",
    "faculty-friction",
    "schools",
    "services",
    "traditions",
    "chronicle",
    "exam",
    "map",
    "forms",
    "bbs",
    "responsive-extras",
    "search",
    "audiences",
    "mytu",
    "eientei",
    "gaokao",
  ],
  locales: ["zh-Hant", "ja", "en"],
};
