import { initI18n } from "./i18n.js";
import { initUI } from "./ui.js";
import { initFaculty } from "./faculty.js";
import { initServices } from "./services.js";
import { initCampusMap } from "./map.js";
import { initResearch } from "./research.js";
import { initBbs } from "./bbs.js";
import { initInfoDialog } from "./info-dialog.js";
import { initCampusInteractions } from "./campus.js";
import { initNews } from "./news.js";
import { initExam } from "./exam.js";
import { initSchools } from "./schools.js";

initInfoDialog();
initUI();
initSchools();
initFaculty();
initServices();
initCampusMap();
initResearch();
initBbs();
initCampusInteractions();
initNews();
initExam();
initI18n();
