import { readFile, writeFile, stat } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { site } from "../site.config.mjs";

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const sourceRoot = path.join(projectRoot, "src");

async function exists(file) {
  try {
    await stat(file);
    return true;
  } catch {
    return false;
  }
}

async function renderIncludes(source, sourceFile) {
  const includePattern = /<!--\s*@include\s+([^\s]+)\s*-->/g;
  const matches = [...source.matchAll(includePattern)];
  let rendered = source;

  for (const match of matches) {
    const includePath = path.resolve(path.dirname(sourceFile), match[1]);
    if (!includePath.startsWith(sourceRoot)) {
      throw new Error(`Include escapes src/: ${match[1]}`);
    }
    if (!(await exists(includePath))) {
      throw new Error(`Missing include: ${path.relative(projectRoot, includePath)}`);
    }
    const partial = await readFile(includePath, "utf8");
    const nested = await renderIncludes(partial, includePath);
    rendered = rendered.replace(match[0], nested.trimEnd());
  }

  return rendered;
}

function masthead(page) {
  if (!page.heading) return "";
  const links = page.links
    .map(([id, label]) => `<a href="#${id}">${label}</a>`)
    .join("");
  return `
    <section class="page-masthead" aria-labelledby="page-title">
      <div class="container">
        <nav class="page-breadcrumb" aria-label="頁面位置">
          <a href="index.html">大學首頁</a><span aria-hidden="true">/</span><b>${page.eyebrow}</b>
        </nav>
        <div class="page-masthead-copy">
          <div><p>${page.eyebrow}</p><h1 id="page-title">${page.heading}</h1></div>
          <p>${page.lead}</p>
        </div>
        <nav class="page-local-nav" aria-label="${page.heading}">${links}</nav>
      </div>
    </section>`;
}

function imagePreload(page) {
  if (!page.preload?.href) return "";
  const responsive = page.preload.srcset
    ? `\n      imagesrcset="${page.preload.srcset}"\n      imagesizes="${page.preload.sizes || "100vw"}"`
    : "";
  return `<link
      rel="preload"
      href="${page.preload.href}"${responsive}
      as="image"
      type="image/webp"
      fetchpriority="high"
    >`;
}

async function buildHtml() {
  const templateFile = path.join(sourceRoot, "index.template.html");
  const template = await readFile(templateFile, "utf8");
  const banner = "<!-- Generated by scripts/build.mjs. Edit src/, not this file. -->\n";
  for (const page of site.pages) {
    const sectionIncludes = page.sections.map((name) => `<!-- @include sections/${name}.html -->`).join("\n");
    const prepared = template
      .replace("<!-- @page-preload -->", imagePreload(page))
      .replace("<!-- @page-masthead -->", masthead(page))
      .replace("<!-- @page-sections -->", sectionIncludes)
      .replaceAll("{{pageId}}", page.id)
      .replaceAll("{{pageTitle}}", page.title)
      .replaceAll("{{pageDescription}}", page.description);
    const included = await renderIncludes(prepared, templateFile);
    const html = included
      .replaceAll("{{portraitSet}}", site.portraitSet)
      .replace(/<img(?![^>]*\bdecoding=)/g, '<img decoding="async"')
      .replace(/^[ \t]+$/gm, "");
    await writeFile(path.join(projectRoot, page.output), banner + html, "utf8");
  }
}

async function buildCss() {
  const parts = [];
  for (const name of site.styles) {
    const file = path.join(sourceRoot, "styles", `${name}.css`);
    if (!(await exists(file))) {
      throw new Error(`Missing stylesheet: src/styles/${name}.css`);
    }
    const content = await readFile(file, "utf8");
    parts.push(`/* src/styles/${name}.css */\n${content.trim()}`);
  }
  const banner = "/* Generated by scripts/build.mjs. Edit src/styles/, not this file. */\n";
  const minified = parts
    .join("\n")
    .replace(/\/\*[\s\S]*?\*\//g, "")
    .replace(/\s+/g, " ")
    .replace(/\s*([{}:;,>])\s*/g, "$1")
    .replace(/;}/g, "}")
    .trim();
  await writeFile(path.join(projectRoot, "styles.css"), banner + minified + "\n", "utf8");
}

await Promise.all([buildHtml(), buildCss()]);
const sectionCount = new Set(site.pages.flatMap((page) => page.sections)).size;
console.log(`Built ${site.pages.length} pages, ${sectionCount} content sections, and ${site.styles.length} stylesheets.`);
