import { readFile, writeFile, stat } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { site } from "../site.config.mjs";

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const sourceRoot = path.join(projectRoot, "src");

async function exists(file) {
  try {
    await stat(file);
    return true;
  } catch {
    return false;
  }
}

async function renderIncludes(source, sourceFile) {
  const includePattern = /<!--\s*@include\s+([^\s]+)\s*-->/g;
  const matches = [...source.matchAll(includePattern)];
  let rendered = source;

  for (const match of matches) {
    const includePath = path.resolve(path.dirname(sourceFile), match[1]);
    if (!includePath.startsWith(sourceRoot)) {
      throw new Error(`Include escapes src/: ${match[1]}`);
    }
    if (!(await exists(includePath))) {
      throw new Error(`Missing include: ${path.relative(projectRoot, includePath)}`);
    }
    const partial = await readFile(includePath, "utf8");
    const nested = await renderIncludes(partial, includePath);
    rendered = rendered.replace(match[0], nested.trimEnd());
  }

  return rendered;
}

async function buildHtml() {
  const templateFile = path.join(sourceRoot, "index.template.html");
  const template = await readFile(templateFile, "utf8");
  const included = await renderIncludes(template, templateFile);
  const html = included.replaceAll("{{portraitSet}}", site.portraitSet);
  const banner = "<!-- Generated by scripts/build.mjs. Edit src/, not this file. -->\n";
  await writeFile(path.join(projectRoot, "index.html"), banner + html, "utf8");
}

async function buildCss() {
  const parts = [];
  for (const name of site.styles) {
    const file = path.join(sourceRoot, "styles", `${name}.css`);
    if (!(await exists(file))) {
      throw new Error(`Missing stylesheet: src/styles/${name}.css`);
    }
    const content = await readFile(file, "utf8");
    parts.push(`/* src/styles/${name}.css */\n${content.trim()}`);
  }
  const banner = "/* Generated by scripts/build.mjs. Edit src/styles/, not this file. */\n";
  await writeFile(path.join(projectRoot, "styles.css"), banner + parts.join("\n\n") + "\n", "utf8");
}

await Promise.all([buildHtml(), buildCss()]);
console.log(`Built ${site.sections.length} sections and ${site.styles.length} stylesheets.`);
